<?xml version="1.0" encoding="UTF-8"?>
<project name="NusaBank" default="default" basedir=".">
    <description>Builds, tests, and runs the project NusaBank.</description>
    <import file="nbproject/build-impl.xml"/>

    <!-- Override run target untuk memastikan JavaFX VM args terbaca -->
    <target name="run" depends="compile">
        <java classname="banking.Main"
              fork="true"
              failonerror="true">
            <classpath>
                <pathelement path="${build.classes.dir}"/>
                <pathelement path="${javac.classpath}"/>
            </classpath>
            <jvmarg value="--module-path"/>
            <jvmarg value="/home/abinbin0s/javafx-sdk/lib"/>
            <jvmarg value="--add-modules"/>
            <jvmarg value="javafx.controls,javafx.fxml"/>
            <jvmarg value="--enable-native-access=javafx.graphics"/>
            <jvmarg value="-Djava.library.path=/home/abinbin0s/javafx-sdk/lib"/>
        </java>
    </target>

</project>